./cub3D ./tests/cub3D/maps/bad/color_invalid_rgb.cub
./cub3D ./tests/cub3D/maps/bad/color_missing.cub
./cub3D ./tests/cub3D/maps/bad/color_missing_ceiling_rgb.cub
./cub3D ./tests/cub3D/maps/bad/color_missing_floor_rgb.cub
./cub3D ./tests/cub3D/maps/bad/color_none.cub
./cub3D ./tests/cub3D/maps/bad/empty.cub
./cub3D ./tests/cub3D/maps/bad/file_letter_end.cub
./cub3D ./tests/cub3D/maps/bad/filetype_missing
./cub3D ./tests/cub3D/maps/bad/filetype_wrong.buc
./cub3D ./tests/cub3D/maps/bad/map_first.cub
./cub3D ./tests/cub3D/maps/bad/map_middle.cub
./cub3D ./tests/cub3D/maps/bad/map_missing.cub
./cub3D ./tests/cub3D/maps/bad/map_only.cub
./cub3D ./tests/cub3D/maps/bad/map_too_small.cub
./cub3D ./tests/cub3D/maps/bad/player_multiple.cub
./cub3D ./tests/cub3D/maps/bad/player_none.cub
./cub3D ./tests/cub3D/maps/bad/player_on_edge.cub
./cub3D ./tests/cub3D/maps/bad/textures_dir.cub
./cub3D ./tests/cub3D/maps/bad/textures_invalid.cub
./cub3D ./tests/cub3D/maps/bad/textures_missing.cub
./cub3D ./tests/cub3D/maps/bad/textures_none.cub
./cub3D ./tests/cub3D/maps/bad/textures_not_xpm.cub
./cub3D ./tests/cub3D/maps/bad/wall_hole_east.cub
./cub3D ./tests/cub3D/maps/bad/wall_hole_north.cub
./cub3D ./tests/cub3D/maps/bad/wall_hole_south.cub
./cub3D ./tests/cub3D/maps/bad/wall_hole_west.cub
./cub3D ./tests/cub3D/maps/bad/wall_none.cub
